schnorr_signature_mvp
VictoriaGrasshopper/schnorr_signature pull request #1
Opened 2023-10-06 12:22 UTC by VictoriaGrasshopper

First version of Schnorr signatures library (include MuSig and simple signatures protocol)

2023-10-06 20:17 UTC, n-romaniv commented on README.md
> +## Usage
I would add a simple usage example, or maybe a link to the examples folder.

2023-10-06 20:17 UTC, n-romaniv commented on src/keys_management.rs
> +    pub public_key: RistrettoPoint,
Does this have to be pub?

2023-10-06 20:17 UTC, n-romaniv commented on src/schnorr_musig/musig_math.rs
> +    message: &String,
It is better to use `&str` or even `AsRef<str>` for ergonomics.

2023-10-06 20:17 UTC, n-romaniv commented on src/schnorr_musig/musig_math.rs
> +pub fn aggregate_s(partial_signatures: &Vec<Scalar>) -> Scalar {
There's generally no reason to accept `&Vec<T>`. You can use `AsRef<[T]>` whenever you need an immutable aka shared reference, which is the case here.

2023-10-06 20:44 UTC, TheBestTvarynka requested changes
good code. I like it. below you can read some advice (take it or leave it):

* usually, functions that create some values based on the random data accept a random number generator as a parameter. [example](https://github.com/Devolutions/sspi-rs/blob/master/src/utils.rs#L41):
```rust
pub fn generate_random_symmetric_key(cipher: &CipherSuite, rnd: &mut OsRng) -> Vec<u8> {
    todo!()
}
```
* [`zeroize`](https://docs.rs/zeroize/latest/zeroize/) crate. it can help clear the memory when the object dropped

2023-10-06 20:44 UTC, TheBestTvarynka commented on src/schnorr_musig/musig_math.rs
> +        panic!("No public keys provided for aggregation.");
do not panic. return an error instead

2023-10-06 20:44 UTC, TheBestTvarynka commented on src/schnorr_musig/musig_math.rs
> +        panic!("No nonce provided for aggregation.");
do not panic

2023-10-06 20:44 UTC, TheBestTvarynka commented on src/schnorr_musig/musig_math.rs
> +    message: &String,
use `&str` or `impl AsRef<str>`

2023-10-06 20:44 UTC, TheBestTvarynka commented on src/schnorr_musig/musig_math.rs
> +pub fn test_valid_signature_with_n_parties(n: usize) -> bool {
shouldn't it be in the `tests` module?

2023-10-07 06:12 UTC, Sakapoi approved these changes

2023-10-07 17:27 UTC, TheBestTvarynka approved these changes

2023-10-08 11:25 UTC, Barsik-sus approved these changes

2023-10-08 11:25 UTC, Barsik-sus commented on src/keys_management.rs
> +    pub fn create<R>(mut rng: R) -> KeyPair
I think it would be more convenient to call it `new`, and the following method would be `new_with_private_key`

2023-10-08 11:25 UTC, Barsik-sus commented on src/schnorr_musig/musig_protocol/aggregator.rs
> +    pub fn new_skip_the_protocol(
What do you think about `builder` instead?

2023-10-08 11:25 UTC, Barsik-sus commented on src/schnorr_musig/musig_protocol/aggregator.rs
> +pub struct Aggregator<'a, S: AggregationState> {
[`Bound behavior, not data`](https://github.com/rust-lang-ua/rust_incubator/tree/master/2_idioms/2_3_bound_impl)

2023-10-08 22:00 UTC, n-romaniv approved these changes

2023-10-10 10:12 UTC, merged